import { createSlice } from "@reduxjs/toolkit";

let i = createSlice({
  name: "shopping--website", 
  initialState: {
    item: [
      {
        id: 1,
        Name: 'PRODUCT-1',
        price: 26,
        img: 'https://m.media-amazon.com/images/I/51L+HCwDtLL._AC_SY300_SX300_.jpg',
        cat: 'Bag',
        type: 'new',
        qty: 1,
      },
      {
        id: 2,
        Name: 'PRODUCT-2',
        price: 96,
        img: 'https://m.media-amazon.com/images/I/81YvgN0CcdL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
        cat: 'Phone',
        type: 'new',
        qty: 1,
      },
      {
        id:3,
        Name:'PRODUCT-3',
        price:26,
        img:'https://m.media-amazon.com/images/I/31urAopo7rL._SX300_SY300_QL70_FMwebp_.jpg',
        cat:'Face-wash',
        type:'new',
        qty:1,
    },
    {
        id:4,
        Name:'PRODUCT-4',
        price:46,
        img:'/perfume.png',
        cat:'Perfume',
        type:'featured',
        qty:1,
    },
    {
        id:5,
        Name:'PRODUCT-5',
        price:55,
        img:'/hairdryer.png',
        cat:'HairDryer',
        type:'featured',
        qty:1,
    },
    {
        id:6,
        Name:'PRODUCT-6',
        price:66,
        img:'https://m.media-amazon.com/images/I/31-daQlUgGL._SX300_SY300_QL70_FMwebp_.jpg',
        cat:'Face Product',
        type:'top',
        qty:1,
    },
    {
        id:7,
        Name:'PRODUCT-7',
        price:66,
        img:'/powerbank.png',
        cat:'charger',
        type:'top',
        qty:1,
    },
       {
        id:8,
        Name:'PRODUCT-8',
        price:66,
        img:'/airpod12.png',
        cat:'airpod',
        type:'top',
        qty:1,
    },
       {
        id:9,
        Name:'PRODUCT-9',
        price:66,
        img:'https://m.media-amazon.com/images/I/41h3+tOcptL._SY300_SX300_.jpg',
        cat:'creame',
        type:'top',
        qty:1,
    },
       {
        id:10,
        Name:'PRODUCT-10',
        price:69,
        img:'https://m.media-amazon.com/images/I/41OGEiqj8aL._SX300_SY300_QL70_FMwebp_.jpg',
        cat:'Comb',
        type:'featured',
        qty:1,
    },
       {
        id:11,
        Name:'PRODUCT-11',
        price:75,
        img:'/facepowder.png',
        cat:'FacePowder',
        type:'new',
        qty:1,
    },
       {
        id:12,
        Name:'PRODUCT-12',
        price:80,
        img:'/speaker.png',
        cat:'Speaker',
        type:'new',
        qty:1,
    },
       {
        id:13,
        Name:'PRODUCT-13',
        price:85,
        img:'/laptop.png',
        cat:'laptop',
        type:'featured',
        qty:1,
    },
       {
        id:14,
        Name:'PRODUCT-14',
        price:95,
        img:'/pharmacy2.png',
        cat:'Medicine',
        type:'featured',
        qty:1,
    },
    ]
  },
  reducers: {}
});
export const selectproduct = (state) => state["shopping--website"].item;
const productreducer = i.reducer;
export default productreducer;
